import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Web3Provider } from "@/components/Web3Provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SERVICES, getServiceBySlug } from "@/lib/services";
import { SITE } from "@/lib/site";
interface Props { params: { slug: string }; }
export function generateStaticParams() { return SERVICES.map((s) => ({ slug: s.slug })); }
export function generateMetadata({ params }: Props): Metadata { const svc=getServiceBySlug(params.slug); return svc?{ title: `${svc.name} — Kenshi QuestPay`, description: svc.description }:{ title:"Service not found — QuestPay"}; }
function List({ title, items }: { title: string; items: string[] }) { return <div className="rounded-2xl border border-white/10 bg-[var(--qp-surface)] p-4"><h3 className="font-sora text-sm font-bold text-white">{title}</h3><ul className="mt-3 space-y-2 text-sm text-muted">{items.map((item)=><li key={item}>• {item}</li>)}</ul></div>; }
export default function ServiceDetailPage({ params }: Props) { const svc=getServiceBySlug(params.slug); if(!svc) notFound(); return <Web3Provider><Navbar/><main className="min-screen-safe pt-20"><section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[1fr_320px]"><div className="glass-panel-strong rounded-[2rem] p-6 sm:p-8 lg:p-10"><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[var(--qp-violet-300)]">{SITE.realNetwork}</p><h1 className="mt-3 font-sora text-4xl font-black text-white">{svc.name}</h1><p className="mt-4 text-lg leading-8 text-secondary">{svc.description}</p><p className="mt-4 rounded-2xl border border-[#8752ff]/20 bg-[#8752ff]/10 p-4 text-sm leading-6 text-secondary">Outcome: {svc.outcome}</p><div className="mt-8 grid gap-4 md:grid-cols-2"><List title="Included" items={svc.included}/><List title="Best requirements" items={svc.requirements}/><List title="Not included" items={svc.excluded}/><List title="Process" items={["Submit a private brief", "Receive locked quote", "Payment verification", "Track delivery"]}/></div><p className="mt-6 text-xs text-subtle">{SITE.disclaimer}</p></div><aside className="lg:sticky lg:top-24 lg:self-start"><div className="rounded-[2rem] border border-white/10 bg-[var(--qp-surface)] p-5"><p className="text-xs uppercase tracking-[0.2em] text-muted">Starting price</p><p className="mt-2 font-mono text-3xl font-black text-white">${svc.usd}</p><div className="mt-5 space-y-3 text-sm text-secondary"><p><b className="text-white">Delivery:</b> {svc.delivery}</p><p><b className="text-white">Revisions:</b> {svc.revisions}</p><p><b className="text-white">Tokens:</b> USDT, fxVERSE, POL</p></div><a href={`/checkout/${svc.slug}`} className="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-2xl bg-verse-purple px-8 py-3 font-bold text-white shadow-[0_0_38px_rgba(124,92,255,.28)] hover:bg-verse-purple/80 transition">Start Order</a><a href="/services" className="mt-3 inline-flex min-h-12 w-full items-center justify-center rounded-2xl border border-white/10 bg-[var(--qp-surface)] px-6 py-3 font-bold text-secondary hover:border-verse-blue/40 hover:bg-verse-blue/10 transition">All services</a></div></aside></div></section></main><Footer/></Web3Provider>; }
