import type { Metadata } from "next";
import Link from "next/link";
import { Web3Provider } from "@/components/Web3Provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SERVICES } from "@/lib/services";
import { SITE } from "@/lib/site";
export const metadata: Metadata = { title: "Services — Kenshi QuestPay", description: "Fixed-price creator services with structured briefs and Polygon payment receipts." };
export default function ServicesPage() { return <Web3Provider><Navbar/><main className="min-screen-safe pt-20"><section id="pricing" className="scroll-mt-28 px-4 py-14 sm:px-6 sm:py-18 lg:px-8"><div className="mx-auto w-full max-w-7xl"><div className="mb-12 text-center"><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[var(--qp-violet-300)]">{SITE.realNetwork}</p><h1 className="section-title mt-3 font-sora font-black text-white">Service <span className="gradient-text">Catalog</span></h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-muted">Productized services with clear scope, delivery targets, and fixed starting prices.</p><p className="mx-auto mt-2 max-w-xl text-sm text-subtle">{SITE.disclaimer}</p></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{SERVICES.map((svc)=><div key={svc.slug} className="group flex flex-col rounded-[1.5rem] p-6 glass-panel hover:border-verse-purple/30 hover:bg-[var(--qp-surface)] transition-all duration-300"><div className="flex items-start justify-between gap-3"><span className="rounded-full border border-white/10 bg-[var(--qp-surface)] px-3 py-1 text-xs font-bold uppercase tracking-[0.14em] text-secondary">{svc.delivery}</span><span className="rounded-full bg-verse-blue/10 px-3 py-1 font-mono text-xs font-bold text-[var(--qp-violet-300)]">${svc.usd} USD</span></div><h2 className="mt-4 font-sora text-lg font-black text-white">{svc.name}</h2><p className="mt-3 flex-1 text-sm leading-6 text-muted">{svc.description}</p><p className="mt-3 text-xs leading-5 text-muted">{svc.outcome}</p><Link href={`/services/${svc.slug}`} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-2xl bg-verse-purple/20 px-4 py-3 font-bold text-[#C1B6FF] border border-verse-purple/30 group-hover:bg-verse-purple/30 transition-all">View package</Link></div>)}</div></div></section></main><Footer/></Web3Provider>; }
