import playwright from '/workspace/kenshi-shipos/node_modules/playwright/index.js';
const { chromium } = playwright;
const base = process.argv[2] || 'http://127.0.0.1:3012';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox','--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on('console', msg => { if (msg.type() === 'error' && !msg.text().includes('analytics.vgdh.io')) errors.push(msg.text()); });
page.on('pageerror', err => errors.push(err.message));
await page.goto(`${base}/#checkout`, { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(1000);
await page.getByRole('button', { name: /Manual Pay/i }).click();
await page.waitForSelector('img[alt="Payment QR"]');
const hasReceive = await page.getByText(/0xA111/i).count();
const hasUSDT = await page.getByText(/USDT/i).count();
if (!hasReceive || !hasUSDT) throw new Error('Manual pay panel missing owner address or USDT token');
await page.getByRole('button', { name: /Testnet Demo/i }).click();
await page.waitForSelector('text=Demo — Base Sepolia');
await page.goto(`${base}/verify?tx=0x0000000000000000000000000000000000000000000000000000000000000000&package=1&token=USDT`, { waitUntil: 'domcontentloaded' });
await page.waitForSelector('text=Verification failed', { timeout: 20000 });
const reason = await page.locator('text=/Transaction not found|failed|Invalid|not found/i').first().textContent();
await browser.close();
if (errors.length) throw new Error(errors.join('\n'));
console.log(`QUESTPAY_SMOKE_PASS bad_verify_reason=${reason?.slice(0,80)}`);
